// docs/examples/base/html/WebComponents/CustomElements.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

const customElementsRef = ref();

onMounted(() => {
  class UserCard extends HTMLElement {
    static get observedAttributes() {
      return ['name', 'age'];
    } // 声明需监听的属性

    constructor() {
      super();
      this.attachShadow({ mode: 'open' }); // 改用 Shadow DOM
      this.shadowRoot.innerHTML = `
      <div class="card">
        <h3></h3>
        <p>Age: <span class="age"></span></p>
      </div>
    `;
    }

    attributeChangedCallback(name, oldVal, newVal) {
      if (name === 'name') {
        this.shadowRoot.querySelector('h3').textContent = newVal;
      } else if (name === 'age') {
        this.shadowRoot.querySelector('.age').textContent = newVal;
      }
    }
  }

  customElements.define('user-card', UserCard);

  const userCard = document.createElement('user-card');
  userCard.setAttribute('name', 'Bob');
  userCard.setAttribute('age', '35');
  customElementsRef.value.appendChild(userCard);
})
</script>

<template>
  <main ref="customElementsRef" class="custom-elements"></main>
</template>

// docs/examples/base/js/WebComponents/CustomElements/index.js
class UserCard extends HTMLElement {
  static observedAttributes = ['name', 'age']

  constructor() {
    super()

    this.attachShadow({ mode: 'open' })
    this.shadowRoot.innerHTML = `
      <style>
        .card {
          border: 1px solid #ccc;
          border-radius: 8px;
          padding: 10px;
          max-width: 200px;
          font-family: sans-serif;
        }
        .age {
          color: #888;
        }
      </style>
      <div class="card">
        <h3></h3>
        <p>年龄: <span class="age"></span></p>
      </div>
    `

    this.nameElement = this.shadowRoot.querySelector('h3')
    this.ageElement = this.shadowRoot.querySelector('.age')
  }

  // 元素的被观察属性变化时触发
  attributeChangedCallback(name, oldVal, newVal) {
    if (name === 'name') {
      this.nameElement.textContent = newVal
    } else if (name === 'age') {
      this.ageElement.textContent = newVal
    }
  }
}

customElements.define('ce-user-card', UserCard) // 注册自定义元素
